split:
  dataset_path: 'Data/Dataset'
  test_ratio: 0.2
  random_state: 42
pretrain-embeddings:
  dataset_info_path: 'Data/Dataset/train.json'
  preprocessing_workers: 8
  w2v:
    destination_dir: 'Data/Models/w2v'
    vector_size: 128
    window: 5
    min_count: 3
    workers: 8
  tfidf:
    destination_dir: 'Data/Models/tfidf'
    stop_words: ["(", ")", ".", "#", ";", ",", ">>", "<<", "{", "}", "[", "]", "'.'", "\"...\"", ">", "<", "std", 
                    "fout", "fin", "++", "--", "<=", ">=", "auto", "auto", "bool","break", "case", "char", "char8_t",
                    "char16_t", "char32_t", "class", "concept", "const", "consteval", "constexpr", "continue", 
                    "decltype", "default", "do", "double", "else", "enum", "explicit","false", "float", "for",
                    "if", "inline", "int", "long", "new", "noexcept", "not", "operator", "private", "protected", 
                    "public", "return", "short", "signed", "sizeof", "static", "struct", "switch", "template", 
                    "this", "true", "union", "unsigned", "using", "virtual", "void", "volatile", "wchar_t", "while"]
    token_pattern: \w+|\+|-|=|!=
    max_features: 10000
generate-embeddings:
  - dataset_info_path: 'Data/Dataset/train.json'
    preprocessing_workers: 8
    w2v:
      destination_dir: 'Data/Embeddings/w2v/train'
      model_path: 'Data/Models/w2v/w2v.model'
    tfidf:
      destination_dir: 'Data/Embeddings/tfidf/train'
      model_path: 'Data/Models/tfidf/tfidf.model'
    safe:
      destination_dir: 'Data/Embeddings/safe/train'
      model_path: '/app/Data/Pretrained_Models/safe/safe_trained_X86.pb'
      instr_conv_path: '/app/Data/Pretrained_Models/safe/i2v/word2id.json'
      max_instr: 150
    unixcoder:
      destination_dir: 'Data/Embeddings/unixcoder/train'
      model_path: '/app/Data/Pretrained_Models/unixcoder-base'
      batch_size: 4
      max_length: 512
      padding: true
    codet5plus:
      destination_dir: 'Data/Embeddings/codet5plus/train'
      model_path: '/app/Data/Pretrained_Models/codet5p-110m-embedding'
      batch_size: 4
      padding: true
    openai:
      destination_dir: 'Data/Embeddings/openai/train'
      model_name: 'text-embedding-3-small'
    mistral:
      destination_dir: 'Data/Embeddings/mistral/train'
      model_name: 'mistral-embed'
    
  - dataset_info_path: 'Data/Dataset/test.json'
    preprocessing_workers: 8
    w2v:
      destination_dir: 'Data/Embeddings/w2v/test'
      model_path: 'Data/Models/w2v/w2v.model'
    tfidf:
      destination_dir: 'Data/Embeddings/tfidf/test'
      model_path: 'Data/Models/tfidf/tfidf.model'
    safe:
      destination_dir: 'Data/Embeddings/safe/test'
      model_path: '/app/Data/Pretrained_Models/safe/safe_trained_X86.pb'
      instr_conv_path: '/app/Data/Pretrained_Models/safe/i2v/word2id.json'
      max_instr: 150
    unixcoder:
      destination_dir: 'Data/Embeddings/unixcoder/test'
      model_path: '/app/Data/Pretrained_Models/unixcoder-base'
      batch_size: 4
      max_length: 512
      padding: true
    codet5plus:
      destination_dir: 'Data/Embeddings/codet5plus/test'
      model_path: '/app/Data/Pretrained_Models/codet5p-110m-embedding'
      batch_size: 4
      padding: true
    openai:
      destination_dir: 'Data/Embeddings/openai/test'
      model_name: 'text-embedding-3-small'
    mistral:
      destination_dir: 'Data/Embeddings/mistral/test'
      model_name: 'mistral-embed'

plot-score-per-samples:
    number_shuffles: 5
    train:
        dataset_info_path: 'Data/Dataset/train.json'
        embeddings_path:
           w2v: 'Data/Embeddings/w2v/train/embeddings.parquet'
           tfidf: 'Data/Embeddings/tfidf/train/embeddings.parquet'
           safe: 'Data/Embeddings/safe/train/embeddings.parquet'
           unixcoder: 'Data/Embeddings/unixcoder/train/embeddings.parquet'
           codet5plus: 'Data/Embeddings/codet5plus/train/embeddings.parquet'
           openai: 'Data/Embeddings/openai/train/embeddings.parquet'
           mistral: 'Data/Embeddings/mistral/train/embeddings.parquet'
    test:
        dataset_info_path: 'Data/Dataset/test.json'
        embeddings_path:
           w2v: 'Data/Embeddings/w2v/test/embeddings.parquet'
           tfidf: 'Data/Embeddings/tfidf/test/embeddings.parquet'
           safe: 'Data/Embeddings/safe/test/embeddings.parquet'
           unixcoder: 'Data/Embeddings/unixcoder/test/embeddings.parquet'
           codet5plus: 'Data/Embeddings/codet5plus/test/embeddings.parquet'
           openai: 'Data/Embeddings/openai/test/embeddings.parquet'
           mistral: 'Data/Embeddings/mistral/test/embeddings.parquet'

validate:
  destination_dir: 'Data/Validation'
  train:
        dataset_info_path: 'Data/Dataset/train.json'
        embeddings_path:
           w2v: 'Data/Embeddings/w2v/train/embeddings.parquet'
           tfidf: 'Data/Embeddings/tfidf/train/embeddings.parquet'
           safe: 'Data/Embeddings/safe/train/embeddings.parquet'
           unixcoder: 'Data/Embeddings/unixcoder/train/embeddings.parquet'
           codet5plus: 'Data/Embeddings/codet5plus/train/embeddings.parquet'
           openai: 'Data/Embeddings/openai/train/embeddings.parquet'
           mistral: 'Data/Embeddings/mistral/train/embeddings.parquet'
  test:
      dataset_info_path: 'Data/Dataset/test.json'
      embeddings_path:
          w2v: 'Data/Embeddings/w2v/test/embeddings.parquet'
          tfidf: 'Data/Embeddings/tfidf/test/embeddings.parquet'
          safe: 'Data/Embeddings/safe/test/embeddings.parquet'
          unixcoder: 'Data/Embeddings/unixcoder/test/embeddings.parquet'
          codet5plus: 'Data/Embeddings/codet5plus/test/embeddings.parquet'
          openai: 'Data/Embeddings/openai/test/embeddings.parquet'
          mistral: 'Data/Embeddings/mistral/test/embeddings.parquet'
  parameters:
    embeddings:
      - w2v
      - tfidf
      - safe
      - openai
      - mistral
      - unixcoder
      - codet5plus
    clustering_algos:
      - kmeans
      - spectral_clustering
      - agglomerative_clustering
          
    